# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  node: circleci/node@4.1.0
  react: thefrontside/react@0.2.0
# Orchestrate or schedule a set of jobs
jobs:
  build-front:
    executor: node/default
    working_directory: ~/cinema-front-end
    steps:
      - react/install
      - react/eslint
      - react/test
      - react/coverage
workflows:
  push:
    jobs:
      - build-front
