# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  node: circleci/node@4.1.0
  react: thefrontside/react@0.2.0
# Orchestrate or schedule a set of jobs
jobs:
  build-front:
    working_directory: ~/cinema-device/cinema-front-end
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout:
          path: ~/cinema-device
      - react/install
      - react/eslint
      - react/test
      - react/coverage
  build-back:
    working_directory: ~/cinema-device/cinema-back-end
    docker:
      - image: circleci/node:14.15
      - image: circleci/postgres:9.6.9-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: cinema_user
          POSTGRES_DB: cinema_device
    steps:
      - checkout:
          path: ~/cinema-device
      - run: yarn add express --save
      - run: yarn install sequelize pg pg-hstore
workflows:
  push:
    jobs:
      - build-front
      - build-back
